name: geiger_dummy_data
description: >-
  A dart package that provides functionality for easy propagation of data to the Geiger localStorage for testing purposes.

version: 0.2.1
repository: https://github.com/nosadaniel/geiger_dummy_data
documentation: https://github.com/cyber-geiger/toolbox-indicator/tree/development-java


environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  equatable: ^2.0.3
  geiger_localstorage: ^0.5.1
  json_annotation: ^4.3.0
  uuid: ^3.0.5

dev_dependencies:
  lints: ^1.0.0
  build_runner: ^2.1.4
  json_serializable: ^6.0.0
  test: ^1.17.10

