name: geiger_dummy_data
description: Provide functionality for easy retrieval  and passing of data in a specific structure, to the geiger local storage.
version: 0.0.1
repository: https://github.com/nosadaniel/geigerDummyData
documentation: https://github.com/cyber-geiger/toolbox-storage/wiki


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  geiger_localstorage: ^0.5.1
  json_annotation: ^4.3.0

dev_dependencies:
  lints: ^1.0.0
  build_runner: ^2.1.4
  json_serializable: ^6.0.0
  test: ^1.17.10

