# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Set up Flutter.
      - name: -> Setup Flutter environment
        uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
        with:
         channel: stable
      - run: flutter doctor -v

       # Checkout gallery code and get packages.
      - name: -> Checkout gallery code
        uses: actions/checkout@v2
      - name: -> Get packages
        run: flutter pub get

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: flutter test
  publish:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          flutter_package: false
          skip_test: true
          
  
